### ISSUE TITLE
Won't apply to Windows 10 Home

### ISSUE THREAD

**Issue by kumbol** [MicrosoftDocs/IntuneDocs.pl-pl#25]
Policies from administrative templates won't get applied on managed Windows 10 Home devices - is that intended or an issue? These docs don't state any end-client license requirements.

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: ce51dccf-30c4-d481-5636-9f77cbd402d4
* Version Independent ID: 3202b1e6-afad-db64-80ec-b0b7cc3ced02
* Content: [Używanie szablonów dla urządzeń z systemem Windows 10 w usłudze Microsoft Intune — Azure](https://docs.microsoft.com/pl-pl/intune/administrative-templates-windows)
* Content Source: [intune/administrative-templates-windows.md](https://github.com/MicrosoftDocs/IntuneDocs.pl-pl/blob/live/intune/administrative-templates-windows.md)
* Service: **microsoft-intune**
* Product: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by CeciAc** [comment]
Hello, @kumbol 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/IntuneDocs/issues/2048

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
